korp_backend_url: http://localhost:1234
languages:
  - value: sme
    label: Davvisámi
  - value: nob
    label: Norsk
  - value: fin
    label: Soumi
  - value: eng
    label: English
has_timespan: false

# anders: autocomplete is currently hard-coded to really only work for
# språkbanken's systems
autocomplete: false
